version: '3'

services:
  frontend:
    #build: ./frontend 
    image: redthorx/pepm_frontend_local
    volumes:
      - static_files:/app/build  # Mount the static files volume
  caddy:
    image: caddy
    ports:
      - "3000:3000"  # use the same port as SITE_ADDRESS, or you will have issues with tls
    volumes:
      - ./web/Caddyfile:/etc/caddy/Caddyfile  # Mount your Caddy configuration, nake sure to change ports
      - static_files:/var/www/static
    environment:
      - SITE_ADDRESS=localhost:3000
  
  example_api: #example api server
    image: traefik/whoami
    command:
      - --port=8080
    ports:
      - "8080:8080"

  login_service:
    #build: ./login
    image: redthorx/mse-chat-login-service
    ports: 
      - "5000:5000"
    env_file:
      - .env
  
  userprofile_service:
    #build: ./login
    image: kedy1ykh/user_profile_app
    ports:
      - "8001:8001"

  quiz_service:
    image: shajinihubert/msegroups-quiz-service
    ports:
      - "5051:5051"

volumes:
     static_files:
